### ISSUE TITLE
serial: fixes, more tests and docstrings.

### ISSUE THREAD

**Issue by nmigen-issue-migration** [nmigen/nmigen-stdio#3]
<a href="https://github.com/jfng"><img src="https://avatars0.githubusercontent.com/u/5796363?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jfng](https://github.com/jfng)**
_Wednesday Jan 01, 2020 at 20:39 GMT_
_Originally opened as https://github.com/m-labs/nmigen-stdio/pull/3_

----

----

_**[jfng](https://github.com/jfng)** included the following code: https://github.com/m-labs/nmigen-stdio/pull/3/commits_

**Comment by jfng** [comment]
Superseded by #5.
